// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    title, description, date, freq, organizer, imgPath, userId
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, title, description, date, freq, organizer, imgpath, userid
`

type CreateEventParams struct {
	Title       string
	Description string
	Date        pgtype.Date
	Freq        string
	Organizer   string
	Imgpath     string
	Userid      int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Date,
		arg.Freq,
		arg.Organizer,
		arg.Imgpath,
		arg.Userid,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Date,
		&i.Freq,
		&i.Organizer,
		&i.Imgpath,
		&i.Userid,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, description, date, freq, organizer, imgpath, userid FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Date,
		&i.Freq,
		&i.Organizer,
		&i.Imgpath,
		&i.Userid,
	)
	return i, err
}

const getEventWithTags = `-- name: GetEventWithTags :one
SELECT
    e.id AS eventId,
    e.title,
    e.description,
    e.date,
    e.freq,
    e.organizer,
    e.imgPath,
    e.userId,
    COALESCE(string_agg(t.name, ','), '') AS tags
FROM
    events e
LEFT JOIN
    event_tags et ON e.id = et.eventId
LEFT JOIN
    tags t ON et.tagId = t.id
WHERE
    e.id = $1
GROUP BY
    e.id, e.title, e.description, e.date, e.freq, e.organizer, e.imgPath, e.userId
`

type GetEventWithTagsRow struct {
	Eventid     int32
	Title       string
	Description string
	Date        pgtype.Date
	Freq        string
	Organizer   string
	Imgpath     string
	Userid      int32
	Tags        interface{}
}

func (q *Queries) GetEventWithTags(ctx context.Context, id int32) (GetEventWithTagsRow, error) {
	row := q.db.QueryRow(ctx, getEventWithTags, id)
	var i GetEventWithTagsRow
	err := row.Scan(
		&i.Eventid,
		&i.Title,
		&i.Description,
		&i.Date,
		&i.Freq,
		&i.Organizer,
		&i.Imgpath,
		&i.Userid,
		&i.Tags,
	)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT id, title, description, date, freq, organizer, imgpath, userid FROM events
`

func (q *Queries) GetEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Date,
			&i.Freq,
			&i.Organizer,
			&i.Imgpath,
			&i.Userid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByOrganizer = `-- name: GetEventsByOrganizer :many
SELECT id, title, description, date, freq, organizer, imgpath, userid FROM events WHERE organizer = $1
`

func (q *Queries) GetEventsByOrganizer(ctx context.Context, organizer string) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByOrganizer, organizer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Date,
			&i.Freq,
			&i.Organizer,
			&i.Imgpath,
			&i.Userid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByOrganizerWithTags = `-- name: GetEventsByOrganizerWithTags :many
SELECT
    e.id AS eventId,
    e.title,
    e.description,
    e.date,
    e.freq,
    e.organizer,
    e.imgPath,
    e.userId,
    COALESCE(string_agg(t.name, ','), '') AS tags
FROM
    events e
LEFT JOIN
    event_tags et ON e.id = et.eventId
LEFT JOIN
    tags t ON et.tagId = t.id
WHERE
    e.organizer = $1
`

type GetEventsByOrganizerWithTagsRow struct {
	Eventid     int32
	Title       string
	Description string
	Date        pgtype.Date
	Freq        string
	Organizer   string
	Imgpath     string
	Userid      int32
	Tags        interface{}
}

func (q *Queries) GetEventsByOrganizerWithTags(ctx context.Context, organizer string) ([]GetEventsByOrganizerWithTagsRow, error) {
	rows, err := q.db.Query(ctx, getEventsByOrganizerWithTags, organizer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByOrganizerWithTagsRow
	for rows.Next() {
		var i GetEventsByOrganizerWithTagsRow
		if err := rows.Scan(
			&i.Eventid,
			&i.Title,
			&i.Description,
			&i.Date,
			&i.Freq,
			&i.Organizer,
			&i.Imgpath,
			&i.Userid,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsWithTags = `-- name: GetEventsWithTags :many
SELECT
    e.id AS eventId,
    e.title,
    e.description,
    e.date,
    e.freq,
    e.organizer,
    e.imgPath,
    e.userId,
    COALESCE(string_agg(t.name, ','), '') AS tags
FROM
    events e
LEFT JOIN
    event_tags et ON e.id = et.eventId
LEFT JOIN
    tags t ON et.tagId = t.id
GROUP BY
    e.id, e.title, e.description, e.date, e.freq, e.organizer, e.imgPath, e.userId
`

type GetEventsWithTagsRow struct {
	Eventid     int32
	Title       string
	Description string
	Date        pgtype.Date
	Freq        string
	Organizer   string
	Imgpath     string
	Userid      int32
	Tags        interface{}
}

func (q *Queries) GetEventsWithTags(ctx context.Context) ([]GetEventsWithTagsRow, error) {
	rows, err := q.db.Query(ctx, getEventsWithTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsWithTagsRow
	for rows.Next() {
		var i GetEventsWithTagsRow
		if err := rows.Scan(
			&i.Eventid,
			&i.Title,
			&i.Description,
			&i.Date,
			&i.Freq,
			&i.Organizer,
			&i.Imgpath,
			&i.Userid,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET
    title = $2,
    description = $3,
    date = $4,
    freq = $5,
    imgPath = $6
WHERE id = $1
`

type UpdateEventParams struct {
	ID          int32
	Title       string
	Description string
	Date        pgtype.Date
	Freq        string
	Imgpath     string
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Date,
		arg.Freq,
		arg.Imgpath,
	)
	return err
}
