// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Organizer struct {
	ID            int64
	OrganizerName string
	Description   string
	ImgUrl        string
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
}
