// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          int32
	Title       string
	Description string
	Date        pgtype.Date
	Freq        string
	Organizer   string
	Imgpath     string
	Userid      int32
}

type EventTag struct {
	Eventid int32
	Tagid   int32
}

type Organizer struct {
	ID            int32
	OrganizerName string
	Description   string
	ImgUrl        string
}

type Tag struct {
	ID   int32
	Name string
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
}
