// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organizers.sql

package database

import (
	"context"
	"database/sql"
)

const countOrganizers = `-- name: CountOrganizers :one
SELECT COUNT(*) FROM organizers
`

func (q *Queries) CountOrganizers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrganizers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizer = `-- name: CreateOrganizer :exec
INSERT INTO organizers (
    organizer_name, description, value, img_url
    ) VALUES (
    ?, ?, ?, ?
)
`

type CreateOrganizerParams struct {
	OrganizerName string
	Description   string
	Value         sql.NullString
	ImgUrl        string
}

func (q *Queries) CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) error {
	_, err := q.db.ExecContext(ctx, createOrganizer,
		arg.OrganizerName,
		arg.Description,
		arg.Value,
		arg.ImgUrl,
	)
	return err
}

const deleteOrganizer = `-- name: DeleteOrganizer :exec
DELETE FROM organizers
WHERE id = ?
`

func (q *Queries) DeleteOrganizer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrganizer, id)
	return err
}

const getOrganizers = `-- name: GetOrganizers :many
SELECT id, organizer_name, description, img_url, value FROM organizers
`

func (q *Queries) GetOrganizers(ctx context.Context) ([]Organizer, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organizer
	for rows.Next() {
		var i Organizer
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerName,
			&i.Description,
			&i.ImgUrl,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
