// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tags.sql

package database

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT (name) DO NOTHING
RETURNING id, name
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const findTagByName = `-- name: FindTagByName :one
;

SELECT id, name
FROM tags
WHERE name = ?
`

func (q *Queries) FindTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, findTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagsForEvent = `-- name: GetTagsForEvent :many
SELECT tags.id, tags.name
FROM tags
JOIN event_tags ON tags.id = event_tags.tagId
WHERE event_tags.eventId = ?
`

func (q *Queries) GetTagsForEvent(ctx context.Context, eventid int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForEvent, eventid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkEventToTag = `-- name: LinkEventToTag :exec
INSERT INTO event_tags (eventId, tagId)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type LinkEventToTagParams struct {
	Eventid int64
	Tagid   int64
}

func (q *Queries) LinkEventToTag(ctx context.Context, arg LinkEventToTagParams) error {
	_, err := q.db.ExecContext(ctx, linkEventToTag, arg.Eventid, arg.Tagid)
	return err
}
